demo_app/urls.py
# -*- coding: utf-8 -*- 
# @Time : 2019-10-08 23:36 
# @Author : derek.zhang 
# @File : urls.py 
# @Software: PyCharm

from django.urls import path
from demo_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('hello/<str:country_name>/', views.hello_country, name='hello'),
    path('add/', views.add, name='add'),
]

demo_porj/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demo_app/', include(('demo_app.urls','demo_app'), namespace='demo_app'))
]

demo_app/models.py
from django.db import models

# Create your models here.
from django.db import models


class Cat(models.Model):
    name = models.CharField(max_length=35)
    age = models.IntegerField()

    def __str__(self):
        return self.name

demo_app/forms.py
from django import forms


class AddFrom(forms.Form):
    name = forms.CharField(required=True, max_length=10,label='name_form')
    age = forms.IntegerField(required=True,label='age_form')

demo_app/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse, Http404
from .models import *
from .forms import AddFrom


def index(request):
    # return HttpResponse("Hello, world. This is your first Django")
    cats_list = Cat.objects.all()
    from django.template import loader
    template = loader.get_template('demo_app/index.html')
    context = {
        'cats_list': cats_list,
    }
    return HttpResponse(template.render(context, request))

def detail(request, id):
    try:
        cat = Cat.objects.get(id = id)
    except Cat.DoesNotExist:
        raise Http404("Cat does not exist")
    return render(request, 'demo_app/detail.html',{'cat':cat})


def add(request):
    if request.method == 'GET':
        # return render(request, 'demo_app/add.html',{})
        form = AddFrom()
        return render(request, 'demo_app/add.html',{'form':form})
    else:
        # name = request.POST['name']
        # age = int(request.POST['age'])
        # cat = Cat(name=name, age=age)
        # cat.save()
        # cats_list = Cat.objects.all()
        # return render(request, 'demo_app/index.html', {'cats_list': cats_list})
        form = AddFrom(request.POST)
        if form.is_valid():
            name = request.POST['name']
            age = int(request.POST['age'])
            cat = Cat(name=name, age=age)
            cat.save()
            cats_list = Cat.objects.all()
            return render(request,'demo_app/index.html',{'cats_list':cats_list})


def hello_country(request, country_name):
    return HttpResponse("Hello,%s" % country_name)

demo_app/templates/demo_app/add.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>add cat</title>
</head>
<body>
    <form action="{% url 'demo_app:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
{#        name:<input  name="name"> </br>#}
{#    age : <input  name="age" ></br>#}


        <input type="submit" value="submit">
    </form>

</body>
</html>

demo_app/templates/demo_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cat List</title>
</head>
<body>
    <table border="1">
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>age</td>
        </tr>
        {% if cats_list %}

        {% for cat in cats_list %}
            <tr>
                <td>{{ cat.id }}</td>
                <td>{{ cat.name }}</td>
                <td>{{ cat.age }}</td>
            </tr>
        {% endfor %}

    {% else %}
        <p>No cat</p>
    {% endif %}
    </table>

</body>
</html>